spring.application.name=deepwallet

# Conexion a MySQL local
spring.datasource.url=jdbc:mysql://localhost:3306/deepwallet?createDatabaseIfNotExist=true&useSSL=false&serverTimezone=UTC
spring.datasource.username=root
spring.datasource.password=
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
server.port=8080
# Hibernate / JPA
spring.jpa.hibernate.ddl-auto=create
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect

fastforex.base-url=https://api.fastforex.io/fetch-one?from=USD&to=CLP&api_key=b6f7e3170e-5936a276ea-tekrx1